languageCode = "pl-PL"
title = "Tworkowski Transport"
baseURL = "/"
theme= "zafta"
ignoreFiles = [".scss"]
canonifyURL = false

[params]
description ="Najpewniejszy międzynarodowy transport ładunków lądowych, fracht i spedycja tylko z LoggerMTS z siedzibą w Raciborzu"
author="DK Commerce & Dealings"
GACode = '11'
company_name = "Tworkowski"
home= "tak"

[[menu.main]]
    name = "O nas"
    weight = -110
    identifier = "about"
    url = "about"
[[menu.main]]
    name = "Oferta"
    weight = -100
    url = "/getting-started/"
[[menu.main]]
    name = "Kontakt"
    weight = -80
    url = "kontakt"
